#include <stdio.h>
int main()
{
    int s,i;
    printf("s : ");
    scanf("%d",&s);
    for ( i=1; i<=s; i++)
    {
        printf("YOU MAKE MY HEART BEAT FASTER WHEN YOU SMILE\nYOUR SIMPLESITY IS YOUR BEAUTY WHICH I LIKE THE MOST\nI ONLY WANT TO SEE YOU WITH A HAPPY SMILE IN YOUR FACE\n BECAUSE OF ME YOU FEEL ANY PAIN, INSECURITY, UNHAPPYNESS I AM SO SORRY FOR THIS\nAND I AM ALSO VERY SORRY FOR MY EVERY BAD BEHAVIOUR AND IMPROPER BEHAVIOUR WITH YOU FROM ME AND BECAUSE OF ME YOU FACE\nI DO NOT LIKE YOUR FACE WITHOUT SMILE. SO PLEASE SMILE IT GLOW YOUR FACE\nI REALY LIKE YOU WITH MY HEART\n              ",i+1);

    }

    return 0;
    
}